### ISSUE TITLE
Support not only infura and alchemy, but regular RPC endpoint

### ISSUE THREAD

**Issue by AndriyKalashnykov** [Pedrojok01/Web3-Boilerplate#1]
Loking in ifura and alchemy is not always preferrable. A lot of web3 developers using own RPC endpoints (just as an example, you can get one at QuickNode and don't need any keys to use that endpoint).

Do you have any plans to support non-vendor locking RPC endpoint?

**Comment by Pedrojok01** [comment]
Oh, this was just given as examples, but you can just use any RPC endpoints instead. You can check in `src/constants/networks.ts` to see how they are used. BSC uses a different one for instance.

Ideally, you should even have 2/3 nodes for each chain that you're using, so if one goes down, you still have a backup node.
